### ISSUE TITLE
[Feature request] Automatically bump package.json version

### ISSUE THREAD

**Issue by afeblot** [mAAdhaTTah/combine-dependabot-prs#14]
Hi,

Thanks a lot for this action, and how it wonderfully deals with conflicts in package-lock.json.

I have actions and packages which are released at every commit to main. Meaning that for every dependabot pull request, or for a combined pull request created by your action, I also need to bump my own version to make releasing possible.

It would be magnificent if your action had an optional parameter to enable automatically bumping the patch number of the package.json version field.

**Comment by mAAdhaTTah** [comment]
Err, you mean bumping the `version` field of the package itself, vs bumping the version of a dependency? If I understand you correctly, I think that's out of scope for this workflow. You can run this workflow and another step as part of your own workflow, if that's something you want to do, but this workflow is more managing dependency versions, not the version of the package itself.

**Comment by afeblot** [comment]
Yes, that's what I meant. Thanks anyway for the quick response.
