### ISSUE TITLE
"Failed to extract version bump info" with long package names

### ISSUE THREAD

**Issue by pownkel** [mAAdhaTTah/combine-dependabot-prs#4]
For longer package names, dependabot [truncates the commit header](https://github.com/dependabot/feedback/issues/165) so that it does not contain the package version (for example, in [this PR](https://github.com/microsoft/web-insights-service/pull/296)). The commit body still contains the version info, but it looks like this package assumes the version will be available in the specific format that dependabot uses for the commit header. When the version numbers are truncated from the commit header, we get the same error as #3.

**Comment by mAAdhaTTah** [comment]
Hmmm, ok. Will have to take a closer look at the commit body. Maybe that's more reliable than the header?

**Comment by mAAdhaTTah** [comment]
Actually, looks like the PR title will work for this. Going to do some testing of this today and should get this resolved this weekend.

**Comment by mAAdhaTTah** [comment]
See #6 – I tested it and it works for me, but would love some additional verification.

**Comment by pownkel** [comment]
Awesome, thank you! I'll try it on our repo once we have some new dependabot PRs to test on

**Comment by pownkel** [comment]
I ran that branch on our repo and had no problems. It works for the package updates that fail with the most recent release 👍
(The [test PR is here](https://github.com/microsoft/web-insights-service/pull/340), eslint-plugin-sort-class-members and @typescript-eslint/eslint-plugin-tslint were both previously failing to parse)

**Comment by mAAdhaTTah** [comment]
Awesome, gonna merge & publish. Thanks for testing!
